---
markmap:
  maxWidth: 300
---

# Tâm lý học về tiền 📚
## **1. Nature of Money and Happiness** 💸
  - Money as a tool, not a goal 🔧
  - Importance of managing behaviors over intelligence 🧠
  - No one’s Crazy in financial decisions 🤪
  - Rationality > correctness ⚖️

## **2. Impact of Luck and Financial Success** 🍀
  - Role of luck in success 🎲
  - Focus on common patterns > specific cases 🔮

## **3. Knowing ENOUGH**
  - Sự đố kỵ khiến bạn trở nên liều lĩnh hơn 🚫👀
    - Vận động viên bóng chày kiếm được 500K/năm → người giàu có vs 1 ngôi sao 36M/year -> không hài lòng
    - Ăn mày sẽ không ghen tị với tỉ phú, nhưng nhất định sẽ ghen tị với gã ăn mày hàng xóm có "thu nhập" nhiều hơn mình hàng ngày
    - Chúng ta tủi thân khi nghe tin đứa bạn học năm xưa giờ đã làm quản lý cao cấp
  - Understanding the limits of wealth for happiness 😊💰
    - Productive Phase -> Diminishing Returns -> Negative Returns
  - Intentional consumption & Unintentional Saving

## **4. Getting Wealthy vs Staying Wealthy**
  - Kiếm tiền dễ dàng hơn giữ nó
  - Sự tự do là lợi ích lớn nhất của tiền
  - Kiểm soát thời gian quyết định hạnh phúc

## **5. Tails, You Win**
  - Tails - cái đuôi dài: Sự kiện nhỏ chiếm phần lớn kết quả
  - chất lượng của thành công > Thất bại
    - Amazon's success came from tail events like Prime and AWS
    - Walt Disney's success with Snow White outshone hundreds of other productions
  - Sức mạnh của sự tích lũy
    - Warren Buffett's wealth grew significantly after age 52, highlighting the power of time and compound interest.

