---
markmap:
  colorFreezeLevel: 2
---

# Hạnh phúc?

## Đơn giản hóa thành 4

- Nội tâm
- Sức khỏe
- Mối quan hệ
- Tài chính

## Nguyên lý ánh sáng

## Nghi vấn tích cực

- Nghi vấn tích cực → ngộ → hiểu → chuyển hóa

## Tam giác hiện thực hạnh phúc

- Thông tin: Hài lòng nội tâm
- Vật chất: cuộc sống số 5: thành công + gia đình + sức khỏe
- Năng lượng: An vui, bao dung, trân trọng - biết ơn

## Cấu trúc con người

- Ác đức (-), Phước đức (+), Công đức (+/-)
- Ngừng tham tưởng -> hài lòng xuất hiện

# Tâm thái hạnh phúc

## Bao dung là gì

## Tính không của vạn vật

## Sĩ thân

## Cội nguồn cuộc sống

- Hạt mầm tâm trí
- Kết quả cuộc sống

## Trân trọng biết ơn

- con người
- ❌ hiển nhiên hình thành
- Ngịch cảnh -> bài học từ nghịch cảnh

## An vui

- Khoái lạc vs An vui

# Hiện thực hóa cuộc sống

## 7 cảnh giới cuộc sống

- Công việc
- Kinh doanh
- Sự nghiệp
- Thành công
- Hạnh phúc
- Giá trị cuộc sống
- Văn hóa

# Quan hệ

## Đạo vợ chồng

- 3 Nhu cầu người chồng
- 3 Nhu cầu người vợ
- 4 điều vợ chồng nên làm
- 4 điểm chung của vợ chộng

## Mối quan hệ

### Mức độ

  + Quen biết: Biết 1 thông tin
  + Quen thuộc: Biết nhiều thông tin
  + Quý mến: Cảm giác Vui vẻ
  + Tin tưởng: Cảm giác an toàn
  + Thân thiết: Tin tưởng toàn diện

### Giúp đối phương thực hiện mong muốn

## Vs Con

### Làm gương vs Thân giáo

### Quản trị cảm xúc

- Nhận diện cảm xúc
- Không lấy thước đo của mình làm tiêu chuẩn

### Lắng nghe, quan tâm, yêu thương

- Nguyên lý ánh sáng: làm lớn ưu điểm
- Tạo bối cảnh
- Nghi vấn tích cục

### Tố chất nhân tài

- Sức học tập
- Nhận lỗi
- Thay đổi
- Cống hiến - Gánh vác
- Kiên trì
- Trân trọng biết ơn
- Khiêm tốn

## Vs người

### 7 bố thí

- Nhan thí: nụ cười
- Nhãn thí: ánh mắt
- Ngôn thí: lời nói
- Tâm thí: Trân trọng - biết ơn
- Thân thí: Giúp người
- Phóng thí: Bao dung
- Tọa thí: Giúp người giống mình

